//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/lang/Exception.java
//
//  Created by raptor on 1/3/14.
//

#ifndef _JavaLangException_H_
#define _JavaLangException_H_

#import "JreEmulation.h"
#include "java/lang/Throwable.h"

#define JavaLangException_serialVersionUID -3387516993124229948LL

@interface JavaLangException : JavaLangThrowable {
}

+ (long long int)serialVersionUID;
- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
- (id)initWithNSString:(NSString *)detailMessage
 withJavaLangThrowable:(JavaLangThrowable *)throwable;
- (id)initWithJavaLangThrowable:(JavaLangThrowable *)throwable;
@end

#endif // _JavaLangException_H_
