//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/lang/Exception.java
//
//  Created by raptor on 1/3/14.
//

#include "java/lang/Exception.h"
#include "java/lang/Throwable.h"

@implementation JavaLangException

+ (NSArray *)memDebugStaticReferences {
  NSMutableArray *result = [NSMutableArray array];
  return result;
}

+ (long long int)serialVersionUID {
  return JavaLangException_serialVersionUID;
}

- (id)init {
  return JreMemDebugAdd([super init]);
}

- (id)initWithNSString:(NSString *)detailMessage {
  return JreMemDebugAdd([super initWithNSString:detailMessage]);
}

- (id)initWithNSString:(NSString *)detailMessage
 withJavaLangThrowable:(JavaLangThrowable *)throwable {
  return JreMemDebugAdd([super initWithNSString:detailMessage withJavaLangThrowable:throwable]);
}

- (id)initWithJavaLangThrowable:(JavaLangThrowable *)throwable {
  return JreMemDebugAdd([super initWithJavaLangThrowable:throwable]);
}

@end
