//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/lang/NullPointerException.java
//
//  Created by raptor on 1/3/14.
//

#include "java/lang/NullPointerException.h"

@implementation JavaLangNullPointerException

+ (NSArray *)memDebugStaticReferences {
  NSMutableArray *result = [NSMutableArray array];
  return result;
}

+ (long long int)serialVersionUID {
  return JavaLangNullPointerException_serialVersionUID;
}

- (id)init {
  return JreMemDebugAdd([super init]);
}

- (id)initWithNSString:(NSString *)detailMessage {
  return JreMemDebugAdd([super initWithNSString:detailMessage]);
}

@end
